version: '3.8'

services:
  flask-backend:
    build: ./backend
    ports:
      - "5008:5008"
    restart: always
    networks:
      mynetwork:
        ipv4_address: 192.168.50.100  # Static IP for Flask backend

  vue-frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - flask-backend
    restart: always
    networks:
      mynetwork:
        ipv4_address: 192.168.50.101  # Static IP for Vue frontend

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24  # Custom subnet

