services:
  backend:
    build: ./backend
    ports:
      - "5008:5000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
